/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],  

  // But you can create a sidebar manually
  teoriaSidebar: [
    'teoria/intro-teoria',
    'teoria/temario',
    {
      type: 'category',
      label: 'Contenido',
      items: [              
              'teoria/content/modulo1',
              'teoria/content/modulo2',
              'teoria/content/modulo3',
              'teoria/content/modulo4',
      ],
    }
  ],
  laboratorioSidebar: [
    'laboratorio/intro-laboratorio',
    {
      type: 'category',
      label: 'Practicas',
      items: [
        'laboratorio/practicas/intro',
      ]
    },
    {
      type: 'category',
      label: 'Recursos',
      items: [
        'laboratorio/recursos/intro',
      ]
    },
    {
      type: 'category',
      label: 'Tutoriales',
      items: [
        'laboratorio/tutoriales/intro',
        {
          type: 'category',
          label: 'Herramientas',
          items: [
            'laboratorio/tutoriales/herramientas/linux',
            'laboratorio/tutoriales/herramientas/gcc',
            'laboratorio/tutoriales/herramientas/make',
            'laboratorio/tutoriales/herramientas/gdb',
            'laboratorio/tutoriales/herramientas/valgrind',
          ]
        },
        'laboratorio/tutoriales/procesos',
        {
          type: 'category',
          label: 'Hilos y sincronización',
          items: [
            'laboratorio/tutoriales/hilos/threads',
            'laboratorio/tutoriales/hilos/sincronizacion',
          ]
        },               
      ]
    },
  ],
  
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
